In [2]:
import pandas as pd
import seaborn as sb
import matplotlib as plt
import numpy as np
import sklearn
import matplotlib.pyplot as mtplt
import re

In [4]:
tweetData = pd.read_csv('featureEngineered.csv', index_col=False)
tweetData

,Unnamed: 0,index,tweet,tweettype,charCount,wordCount,sentenceCount,capCharCount,capWordCount,quotedWordCount,stopwordCount,uniqueWordCount,hashCount,mentionCount,punctCount,avgWordLen,modTweet
0,0,0,@ZubairSabirPTI pls dont insult the word 'Molna',anger,49,7,1,6,0,0,1,7,0,0,"{'! count': 0, '"" count': 0, '# count': 0, '$ ...",7.000000,"['ZubairSabirPTI', 'pls', 'dont', 'insult', 'w..."
1,1,1,@ArcticFantasy I would have almost took offens...,anger,81,14,1,4,2,0,5,13,0,0,"{'! count': 0, '"" count': 0, '# count': 0, '$ ...",5.785714,"['ArcticFantasy', 'I', 'would', 'almost', 'tak..."
2,2,2,@IllinoisLoyalty that Rutgers game was an abom...,anger,114,20,3,6,0,0,8,20,0,0,"{'! count': 0, '"" count': 0, '# count': 0, '$ ...",5.700000,"['IllinoisLoyalty', 'Rutgers', 'game', 'abomin..."
3,3,3,@CozanGaming that's what lisa asked before she...,anger,90,16,2,3,1,0,7,16,0,0,"{'! count': 0, '"" count': 0, '# count': 0, '$ ...",5.625000,"['CozanGaming', 'lisa', 'ask', 'start', 'rag',..."
4,4,4,Sometimes I get mad over something so minuscul...,anger,133,25,1,3,2,0,7,22,0,0,"{'! count': 0, '"" count': 0, '# count': 0, '$ ...",5.320000,"['Sometimes', 'I', 'get', 'mad', 'something', ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43955,43955,43955,@JohnLloydTaylor,neutral,16,1,1,3,0,0,0,1,0,0,"{'! count': 0, '"" count': 0, '# count': 0, '$ ...",16.000000,['JohnLloydTaylor']
43956,43956,43956,Happy Mothers Day All my love,love,30,6,1,4,0,0,1,6,0,0,"{'! count': 0, '"" count': 0, '# count': 0, '$ ...",5.000000,"['Happy', 'Mothers', 'Day', 'All', 'love']"
43957,43957,43957,Happy Mother's Day to all the mommies out ther...,love,123,25,1,3,0,0,15,23,0,0,"{'! count': 1, '"" count': 0, '# count': 0, '$ ...",4.920000,"['Happy', 'Mother', 'Day', 'mommy', 'woman', '..."
43958,43958,43958,@niariley WASSUP BEAUTIFUL!!! FOLLOW ME!! PEE...,joy,122,19,5,83,18,0,0,19,0,0,"{'! count': 7, '"" count': 0, '# count': 0, '$ ...",6.421053,"['niariley', 'WASSUP', 'BEAUTIFUL', 'FOLLOW', ..."
43959,43959,43959,@mopedronin bullet train from tokyo the gf ...,love,131,18,1,0,0,0,6,18,0,0,"{'! count': 0, '"" count': 0, '# count': 0, '$ ...",7.277778,"['mopedronin', 'bullet', 'train', 'tokyo', 'gf..."

In [7]:
tweetData = tweetData.drop(['Unnamed: 0', 'index'], axis = 1)

In [10]:
def count_punctuations(tweet):
    punctuations='!"#$%&\'()*+,-./:;<=>?@[\]^_`{|}~'
    d=dict()
    for i in punctuations:
        d[str(i)+' count']=tweet.count(i)
    return d

for i, tweet in enumerate(tweetData['tweet']):
  dictPunct = count_punctuations(tweet)
  for key,val in dictPunct.items():
    tweetData.loc[i,key] = val

In [11]:
tweetData.head()

,tweet,tweettype,charCount,wordCount,sentenceCount,capCharCount,capWordCount,quotedWordCount,stopwordCount,uniqueWordCount,...,[ count,\ count,] count,^ count,_ count,` count,{ count,| count,} count,~ count
0,@ZubairSabirPTI pls dont insult the word 'Molna',anger,49,7,1,6,0,0,1,7,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,@ArcticFantasy I would have almost took offens...,anger,81,14,1,4,2,0,5,13,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,@IllinoisLoyalty that Rutgers game was an abom...,anger,114,20,3,6,0,0,8,20,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,@CozanGaming that's what lisa asked before she...,anger,90,16,2,3,1,0,7,16,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Sometimes I get mad over something so minuscul...,anger,133,25,1,3,2,0,7,22,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [12]:
tweetData.to_csv('featureEngineered2.csv')